name: Generate Visualizations

on:
  push:
    branches: [main]
    paths:
      - "*.py"
      - "requirements.txt"

jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate visualizations
        run: |
          python run.py --feature 1
          python run.py --feature 2
          python run.py --feature 3
          python run.py --feature 4
          python run.py --feature 5
          python run.py --feature 6
      - name: Upload visualization artifacts
        uses: actions/upload-artifact@v4
        with:
          name: visualizations
          path: |
            results/contributor_analysis_results/images/*.png
            results/label_analysis/images/*.png
            results/label_analysis_area_repo/images/*.png
            results/Timeline Analysis/*.png
            results/complexity_analysis/images/*.png
            results/network_analysis/images/*.png
            results/resolution_prediction/images/*.png